// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProvider":       schema_pkg_apis_lotaprovider_v1alpha1_LotaProvider(ref),
		"github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProviderSpec":   schema_pkg_apis_lotaprovider_v1alpha1_LotaProviderSpec(ref),
		"github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProviderStatus": schema_pkg_apis_lotaprovider_v1alpha1_LotaProviderStatus(ref),
	}
}

func schema_pkg_apis_lotaprovider_v1alpha1_LotaProvider(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LotaProvider is the Schema for the lotaproviders API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProviderSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProviderStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProviderSpec", "github.com/mcanevet/lota-operator/pkg/apis/lotaprovider/v1alpha1.LotaProviderStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_lotaprovider_v1alpha1_LotaProviderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LotaProviderSpec defines the desired state of LotaProvider",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_lotaprovider_v1alpha1_LotaProviderStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LotaProviderStatus defines the observed state of LotaProvider",
				Type:        []string{"object"},
			},
		},
	}
}
