apiVersion: apps/v1
kind: Deployment
metadata:
  name: lota-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lota-operator
  template:
    metadata:
      labels:
        name: lota-operator
    spec:
      serviceAccountName: lota-operator
      containers:
        - name: lota-operator
          # Replace this with the built image name
          image: docker.io/mcanevet/lota-operator
          command:
          - lota-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "lota-operator"
